# Generated by Django 5.1.5 on 2025-03-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_message_options_remove_message_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='icon',
            field=models.ImageField(blank=True, default='default_group.jpg', null=True, upload_to='group_icons/'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
